sudo: required
dist: trusty
branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libhunspell-1.3-0 hunspell-en-us libhunspell-dev
  - cd Text-Hoborg
  - cpanm  ExtUtils::PkgConfig
script: "perl Makefile.PL && make test"
